SolComercioParte2/ClienteMVC/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;

namespace ClienteMVC.Controllers
{
    public class BancoController : Controller
    {
        public BancoLN oBancoLN { get { return new BancoLN(); } }

        public ActionResult Index(string txtFiltro = "")
        {
            List<Banco> lista = new BancoLN().Listar_Banco(txtFiltro);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_ListadoBanco", lista);
            }

            return View(lista);
        }


        public ActionResult Editar(int IdBanco = 0)
        {
            Banco banco;
            if (IdBanco == 0)
            {
                banco = new Banco();
            }
            else
            {
                banco = oBancoLN.Recuperar_Banco_PorCodigo(IdBanco);
            }

            return PartialView("_EditarBanco", banco);
        }

        public ActionResult GrabarBanco(Banco banco)
        {

            if (ModelState.IsValid)
            {
                try
                {


                    if (banco.IdBanco == 0)
                    {
                        oBancoLN.Insertar_Banco(banco);
                    }
                    else
                    {
                        oBancoLN.Actualizar_Banco(banco);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("*", ex.Message);
                    //Grabar log
                    //throw;
                }
            }

            return PartialView("_EditarBancoCuerpo", banco);
        }

    }
}

SolComercioParte2/ClienteMVC/Controllers/OrdenPagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;
using Utilitario;

namespace ClienteMVC.Controllers
{
    public class OrdenPagoController : Controller
    {
        //
        #region AccesosLN

        public BancoLN oBancoLN { get { return new BancoLN(); } }
        public SucursalLN oSucursalLN { get { return new SucursalLN(); } }
        public OrdenPagoLN oOrdenPagoLN { get { return new OrdenPagoLN(); } }
        public TipoLN oTipoLN { get { return new TipoLN(); } }

        #endregion

        public ActionResult Index(int IdSucursal = 0, int TipoMoneda = 0, int TipoSituacion = 0)
        {

            List<OrdenPago> lista = oOrdenPagoLN.Listar_OrdenPago(IdSucursal, TipoMoneda, TipoSituacion);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ListaOrdenPago", lista);
            }
            else
            {
                LlenarViewBag();
                return View(lista);
            }

        }

        [HttpGet]
        public ActionResult Editar(int IdOrdenPago = 0)
        {

            OrdenPago op;
            if (IdOrdenPago == 0)
            {
                op = new OrdenPago();
                op.FechaPago = DateTime.Now;
            }
            else
            {
                op = oOrdenPagoLN.Recuperar_OrdenPago_PorCodigo(IdOrdenPago);
            }

            LlenarViewBag();
            return View(op);

        }

        [HttpPost]
        public ActionResult Editar(OrdenPago OrdenPago)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (OrdenPago.IdOrdenPago == 0)
                    {
                        oOrdenPagoLN.Insertar_OrdenPago(OrdenPago);
                    }
                    else
                    {
                        oOrdenPagoLN.Actualizar_OrdenPago(OrdenPago);
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("*", ex.Message);
                }
            }
            LlenarViewBag();
            return View(OrdenPago);

        }

        private void LlenarViewBag()
        {
            List<Sucursal> listaSucursal = oSucursalLN.Listar_Sucursal();
            listaSucursal.Insert(0, new Sucursal() { IdSucursal = 0, NombreBancoSucursal = "<< TODOS >> "});
            ViewBag.ListaSucursal = listaSucursal;

            List<EnumTipos> lista = new List<EnumTipos>();
            lista.Add(EnumTipos.TipoMoneda);
            lista.Add(EnumTipos.TipoSituacionOrdenPago);
            Dictionary<EnumTipos, List<Tipo>> parametro = oTipoLN.Listar_Tipo_PorGrupo(lista);

            Tipo tipoNuevo = new Tipo() { IdTipo = 0, Nombre = " << TODOS >> "};
            parametro[EnumTipos.TipoMoneda].Insert(0, tipoNuevo);
            parametro[EnumTipos.TipoSituacionOrdenPago].Insert(0, tipoNuevo);

            ViewBag.ListaTipos = parametro;
        }
    }
}

SolComercioParte2/ClienteMVC/Controllers/SucursalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entidades;
using Negocio;
using Utilitario;

namespace ClienteMVC.Controllers
{
    public class SucursalController : Controller
    {
        //
        #region AccesosLN

        public BancoLN oBancoLN { get { return new BancoLN(); } }
        public SucursalLN oSucursalLN { get { return new SucursalLN(); } }

        #endregion

        public ActionResult Index(int IdBancoPar = 0)
        {

            List<Sucursal> lista = oSucursalLN.Listar_Sucursal_PorBanco(IdBancoPar);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ListadoSucursal", lista);
            }
            else
            {
                List<Banco> listaBanco = oBancoLN.Listar_Banco("");
                ViewBag.ListaBanco = listaBanco;
                return View(lista);
            }

        }

        [HttpGet]
        public ActionResult Editar(int IdSucursal = 0)
        {

            Sucursal sucursal;
            if (IdSucursal == 0)
            {
                sucursal = new Sucursal();
                sucursal.FechaRegistro = DateTime.Now;
            }
            else
            {
                sucursal = oSucursalLN.Recuperar_Sucursal_PorCodigo(IdSucursal);
            }
            List<Banco> listaBanco = oBancoLN.Listar_Banco("");
            ViewBag.ListaBanco = listaBanco;
            return View(sucursal);

        }


        public ActionResult Editar(Sucursal sucursal)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    if (sucursal.IdSucursal == 0)
                    {
                        oSucursalLN.Insertar_Sucursal(sucursal);
                    }
                    else
                    {
                        oSucursalLN.Actualizar_Sucursal(sucursal);
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("*", "no se pudo grabar los datos. " + ex.Message);

                }
            }
            List<Banco> listaBanco = oBancoLN.Listar_Banco("");
            ViewBag.ListaBanco = listaBanco;
            return View(sucursal);

        }

    }
}

SolComercioParte2/ClienteMVC/Views/Banco/Index.cshtml
@using Entidades
@model IEnumerable<Banco>

@{
    ViewBag.Title = "Bancos";
}

@using (Ajax.BeginForm(
    "Index",
    "Banco",
    null,
     new AjaxOptions
     {
         HttpMethod = "GET",
         InsertionMode = InsertionMode.Replace,
         UpdateTargetId = "SeccionListaBanco"
     },
    new { id = "frmBanco" }))
{

    <div class="panel-group" id="accordion">
        <!-- PARAMETROS DE BUSQUEDA -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 class="text-left">
                    <a data-toggle="collapse" href="#collapseDatos">
                        <span class="indicador glyphicon glyphicon-chevron-up" aria-hidden="true"></span>  Parametros de Búsqueda
                    </a>
                </h5>
            </div>
        </div>
        <div id="collapseDatos" class="panel-collapse collapse in">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="row form-horizontal">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-md-1">Filtro</label>
                                    <div class="col-md-11">
                                        <div class="input-group">
                                            <input type="text" id="txtFiltro" name="txtFiltro" class="form-control input-sm" placeholder="Ingrese parámetros de busqueda">
                                            <span class="input-group-btn">

                                                <button type="submit" class="btn btn-default btn-sm" id="btnBuscar" name="btnBuscar">
                                                    <span class="glyphicon glyphicon-search"></span>&nbsp;Buscar
                                                </button>
                                                
                                                <button type="button" class="btn btn-sm btn-primary modalGC"
                                                        data-url="@Url.Action("Editar", "Banco")"
                                                        value="Nuevo">
                                                    <span class="glyphicon glyphicon-plus"></span>
                                                    &nbsp;Nuevo
                                                </button>
                                                
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <!-- RESULTADOS -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h5 class="text-left">
                    <a class="" data-toggle="collapse"
                       href="#collapseOne">
                        <span class="indicador glyphicon glyphicon-chevron-up" aria-hidden="true"></span>  Resultados de la Búsqueda
                    </a>
                </h5>
            </div>

            <!--  -->

            <div style="height: auto;" id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                    <div class="row form-horizontal">
                        <div class="col-md-12">
                            <div id="SeccionListaBanco">
                                @Html.Partial("_ListadoBanco", Model)
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--  -->

        </div>
    </div>
}


<script type="text/javascript">

  

    function CargarModal() {
        $.get(globalRutaServidor + "Aplicacion/Editar",
        {
            //  IdSector: $("#IdSector").val()
            IdGrupo: $("#IdGrupo").val()
        }, function (data) {
            $(".seccionModal").html(data);
            $("#contenedor").modal("show");

            $(".modal-content").draggable({
                handle: ".modal-header",
                cursor: "move"
            });
        });
    }

    function CerrarVentana() {
        $("#contenedor").modal("hide");
        $("#frmBanco").submit();
    }

    function toggleChevron(e) { $(e.target).prev('.panel-heading').find("span.indicador").toggleClass('glyphicon-chevron-down glyphicon-chevron-up') }
    $('#accordion').on('shown.bs.collapse', toggleChevron);
    $('#accordion').on('hidden.bs.collapse', toggleChevron);

</script>




SolComercioParte2/ClienteMVC/Views/Banco/_EditarBanco.cshtml
@using Entidades
@model Banco


<div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-header" style="cursor: pointer;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                &times;
            </button>
            @if (Model.IdBanco != 0)
            {
                <h5 class="modal-title">
                    Actualizar Banco
                </h5>
            }
            else
            {
                <h5 class="modal-title">
                    Registrar Banco
                </h5>
            }
        </div>

        @using (Ajax.BeginForm("GrabarBanco", "Banco",
            new AjaxOptions()
            {
                OnComplete = "Finalizado",
                UpdateTargetId = "ParcialEditarBanco"
            }, new { @id = "frmGrabarBanco" }))
        {
            <div class="modal-body" id="ParcialEditarBanco">
                @Html.Partial("_EditarBancoCuerpo", Model)

            </div>



            <div class="modal-footer">
                <div class="btn-group">


                    <button type="submit" id="btnGrabarBanco" class="btn btn-primary btn-sm">
                        Grabar
                    </button>

                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                        Cancelar
                    </button>
                </div>
            </div>
        }

    </div>
</div>


<script type="text/javascript">



    function Finalizado() {
        if ($("#hdError").val() == "0") {
            bootbox.alert("La aplicación se guardó correctamente")
            parent.CerrarVentana();
        }
    }

</script>

SolComercioParte2/ClienteMVC/Views/Banco/_EditarBancoCuerpo.cshtml
@using Entidades

@model Banco

@{

    string mensajePlaceholder = "Datos Obligatorios";

}

<div class="row">

    <div class="col-md-12">

        <div class="row form-horizontal">
            <div class="col-sm-12 col-md-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Nombre, new
                                                {
                                                    @class = "form-control input-sm",
                                                    placeholder = mensajePlaceholder,
                                                    @maxlength = "50"
                                                })
                    </div>
                </div>
            </div>
        </div>

        <div class="row form-horizontal">
            <div class="col-sm-12 col-md-12">
                <div class="form-group">
                    <label for="uDireccionAplicacion" class="col-md-3 control-label">Dirección</label>
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.Direccion, new
                             {
                                 @class = "form-control input-sm",
                                 placeholder = mensajePlaceholder,
                                 @maxlength = "50"
                             })


                    </div>

                </div>
            </div>
        </div>
       
    </div>
</div>
@Html.HiddenFor(m => m.IdBanco)
@Html.HiddenFor(m => m.FlgEliminado)
@Html.HiddenFor(m => m.FechaRegistro)

@if (!ViewData.ModelState.IsValid)
{
    <div class="row">
        <div class="col-md-12">
            <div class="row form-horizontal">
                <div class="col-sm-12 col-md-12 alert alert-warning alert-dismissible">
                    <div class="form-group">
                        <div class="col-sm-12 col-md-12">
                            @Html.ValidationSummary(false, "Revisar los errrores")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (ViewData.ModelState.IsValid)
{
    @Html.Hidden("hdError", "0")
}
else
{
    @Html.Hidden("hdError", "-1")
}







SolComercioParte2/ClienteMVC/Views/Banco/_ListadoBanco.cshtml
@using Entidades
@model IEnumerable<Banco>


@{
}


<script>
    $(window).on('load', function () {
        $('.selectpicker').selectpicker();
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table id="tableMain" class="table table-striped table-bordered table-hover table-condensed">
                <thead class="small">
                    <tr class="text-center">
                        <th class="col-md-1 text-center" scope="col">Codigo</th>
                        <th class="col-md-3 text-center" scope="col">Nombre</th>
                        <th class="col-md-3 text-center" scope="col">Direccion</th>
                        <th class="col-md-2 text-center" scope="col">Acciones</th>
                    </tr>

                </thead>

                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        int contador = 0;
                        foreach (var item in Model)
                        {
                            contador++;
                            <tr id="@contador">
                                <td class="text-center">@item.IdBanco</td>
                                <td class="text-center">@item.Nombre</td>
                                <td class="text-center">@item.Direccion</td>

                                <td align="center">
                                    <button type="button" class="btn btn-default btn-xs modalGC" title="Editar"
                                            data-url="@Url.Action("Editar", "Banco", new { IdBanco = item.IdBanco })">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                    </button>

                                    

                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">No hay registros</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


SolComercioParte2/ClienteMVC/Views/OrdenPago/_ListaOrdenPago.cshtml
@using Entidades
@model IEnumerable<OrdenPago>


@{

}


<script>
    $(window).on('load', function () {
        $('.selectpicker').selectpicker();
    });
</script>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table id="tableMain" class="table table-striped table-bordered table-hover table-condensed">
                <thead class="small">
                    <tr class="text-center">
                        <th class="col-md-1 text-center" scope="col">Codigo</th>
                        <th class="col-md-1 text-center" scope="col">Fecha</th>
                        <th class="col-md-3 text-center" scope="col">Sucursal</th>
                        <th class="col-md-1 text-center" scope="col">Moneda</th>
                        <th class="col-md-1 text-center" scope="col">Monto</th>
                        <th class="col-md-1 text-center" scope="col">Situacion</th>
                        <th class="col-md-1 text-center" scope="col">Acciones</th>
                    </tr>

                </thead>

                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center">@item.IdOrdenPago</td>
                                <td class="text-center">@item.FechaPago.ToString("dd/MM/yyyy")</td>
                                <td class="text-center">@item.NombreSucursalCompleta</td>
                                <td class="text-center">@item.NombreMoneda</td>
                                <td class="text-center">@item.Monto</td>
                                <td class="text-center">@item.NombreSituacion</td>
                                <td align="center">
                                    <a class="btn btn-default btn-xs" title="Editar"
                                            href="@Url.Action("Editar", "OrdenPago", new { IdOrdenPago = item.IdOrdenPago })">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                    </a>



                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="7">No hay registros</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


SolComercioParte2/ClienteMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>GRUPO COMERCIO</title>

    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/css/styles.dhh.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/util.dhh.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Desplegar navegación</span> <span class="icon-bar"></span>
                <span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="padding: 0">
                <img src="~/Content/img/Logocomercio2.jpg" />
            </a>
        </div>
        <div id="menuTop" class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-user"></i>Invitado <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Iniciar Sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div class="separatorPage-dhh">
    </div>
    <div class="container-fluid">
        <div class="row" id="contentDocument">
            <div class="arrowColapse">
                <i class="fa fa-chevron-circle-right fa-2x"></i>
            </div>
            <div id="menuLeft">
                <ul class="menuDHH">
                    <li><a href="@Url.Action("Index", "Banco")"><i class="fa fa-angle-right"></i>Banco</a></li>
                    <li><a href="@Url.Action("Index", "Sucursal")"><i class="fa fa-tasks"></i>Sucursales</a></li>
                    <li><a href="@Url.Action("Index", "OrdenPago")"><i class="fa fa-file-excel-o"></i>Orden Pago</a></li>
                </ul>
            </div>
            <div id="contentRight" class="col-xs-12 col-md-12">
                @if (!string.IsNullOrEmpty(ViewBag.Title))
                {
                    <div class="titlePage">
                        @ViewBag.Title
                    </div>
                }
                <div class="container-fluid">
                    @RenderBody()

                </div>
            </div>
        </div>
        <footer class="footer">
            Todos los derechos reservados @DateTime.Now.Year
            <i class="fa fa-phone"></i>
            (511) 708-9999
            <i class="fa fa-mail-forward"></i>
            msalvador@hotmail.com
        </footer>
    </div>

    <div id="contenedor" class='modal fade in contenedor'
         data-backdrop="static" data-keyboard="true">
        <div class='seccionModal'>
        </div>
    </div>
</body>
</html>

SolComercioParte2/ClienteMVC/Views/Sucursal/_ListadoSucursal.cshtml
@using Entidades
@model IEnumerable<Sucursal>


@{
}

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table id="tableMain" class="table table-striped table-bordered table-hover table-condensed">
                <thead class="small">
                    <tr class="text-center">
                        <th class="col-md-1 text-center" scope="col">Codigo</th>
                        <th class="col-md-3 text-center" scope="col">Nombre</th>
                        <th class="col-md-3 text-center" scope="col">Direccion</th>
                        <th class="col-md-3 text-center" scope="col">Banco</th>
                        <th class="col-md-2 text-center" scope="col">Acciones</th>
                    </tr>

                </thead>

                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        int contador = 0;
                        foreach (var item in Model)
                        {
                            contador++;
                            <tr id="@contador">
                                <td class="text-center">@item.IdSucursal</td>
                                <td class="text-center">@item.Nombre</td>
                                <td class="text-center">@item.Direccion</td>
                                <td class="text-center">@item.NombreBanco</td>
                                <td align="center">
                                    <a  class="btn btn-default btn-xs modalGC" title="Editar"
                                            href="@Url.Action("Editar", "Sucursal", new { IdSucursal = item.IdSucursal })">
                                        <i class="glyphicon glyphicon-pencil"></i>
                                    </a>

                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="4">No hay registros</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
